added jv-spring-rest-hw solution
mate-academy/jv-spring-rest pull request #60
Opened 2021-08-19 18:47 UTC by Basilius-Third

2021-08-19 18:53 UTC, nikdagaev requested changes

2021-08-19 18:53 UTC, nikdagaev commented on src/main/java/mate/academy/spring/service/mapper/CinemaHallDtoMapper.java
> +    public CinemaHallResponseDto parse(CinemaHall cinemaHall) {
эти методы лучше назвать toDto, по аналогии с toModel

2021-08-19 18:57 UTC, nikdagaev approved these changes

2021-08-20 13:09 UTC, KseniiaMakarova requested changes

2021-08-20 13:09 UTC, KseniiaMakarova commented on src/main/java/mate/academy/spring/controller/CinemaHallController.java
> +@RequestMapping("/cinema_halls")
```suggestion
@RequestMapping("/cinema-halls")
```

2021-08-20 13:09 UTC, KseniiaMakarova commented on src/main/java/mate/academy/spring/controller/CinemaHallController.java
> +    public List<CinemaHallResponseDto> getAllCinemaHalls() {
```suggestion
    public List<CinemaHallResponseDto> getAll() {
```

2021-08-20 13:09 UTC, KseniiaMakarova commented on src/main/java/mate/academy/spring/controller/MovieController.java
> +    public List<MovieResponseDto> getAllMovies() {
```suggestion
    public List<MovieResponseDto> getAll() {
```

2021-08-20 13:09 UTC, KseniiaMakarova commented on src/main/java/mate/academy/spring/controller/MovieSessionController.java
> +@RequestMapping("/movie_sessions")
```suggestion
@RequestMapping("/movie-sessions")
```

2021-08-20 13:09 UTC, KseniiaMakarova commented on src/main/java/mate/academy/spring/controller/MovieSessionController.java
> +    public List<MovieSessionResponseDto> getAvailableSession(@RequestParam Long movieId,
```suggestion
    public List<MovieSessionResponseDto> getAvailableSessions(@RequestParam Long movieId,
```

2021-08-20 13:09 UTC, KseniiaMakarova commented on src/main/java/mate/academy/spring/service/mapper/CinemaHallDtoMapper.java
> +
redundant empty line

2021-08-20 13:09 UTC, KseniiaMakarova commented on src/main/java/mate/academy/spring/service/mapper/MovieDtoMapper.java
> +
same

2021-08-20 13:58 UTC, KseniiaMakarova approved these changes

2021-11-16 16:56 UTC, closed without merging